/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import Control.Cdevedor;
import Control.Cdividas;
import Control.Clogin;
import Control.Cpagamento;
import Modal.Mdevedor;
import Modal.Mdivida;
import Modal.Mpagamento;
import Modal.Vdivida;
import Modal.vpagamento;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TEODORO
 */
public class DIVIDA extends javax.swing.JFrame {

    /**
     * Creates new form entrada
     */
    String idf, data;
    double valor_pago, divida, total;
    int id = 0, v = 0, codigo, codigodiv, codidivida, fatura, pag;

    public DIVIDA() {
        initComponents();
        pesquisar("");
        listardivi();
        Control.Clogin l = new Clogin();
        idf = l.recuprarValor(0);
        txtpagamento.setEnabled(false);
        txtdatapagamento.setEnabled(false);
        btnpagamento.setEnabled(false);
        list_pag();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnsalvar = new rojeru_san.RSButton();
        txtnome = new rojeru_san.RSMTextFull();
        cbgenero = new javax.swing.JComboBox();
        txtbi = new rojeru_san.RSMTextFull();
        txttelefone = new rojeru_san.RSMTextFull();
        txtmorada = new rojeru_san.RSMTextFull();
        btnactualizar = new rojeru_san.RSButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtpesquisar = new rojeru_san.RSMTextFull();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbcadastro = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbdivida = new javax.swing.JTable();
        txtdivida = new rojeru_san.RSMTextFull();
        txtfatura = new rojeru_san.RSMTextFull();
        txtdatadivi = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        btndivida = new rojeru_san.RSButton();
        jPanel4 = new javax.swing.JPanel();
        txtpagamento = new rojeru_san.RSMTextFull();
        txtdatapagamento = new javax.swing.JFormattedTextField();
        btnpagamento = new rojeru_san.RSButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbpagamento = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel6.setBackground(new java.awt.Color(52, 58, 115));

        btnsalvar.setBackground(new java.awt.Color(255, 102, 0));
        btnsalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/salvar.png"))); // NOI18N
        btnsalvar.setText("GUARDAR");
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });

        txtnome.setPlaceholder("NOME ");
        txtnome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnomeKeyPressed(evt);
            }
        });

        cbgenero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbgenero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECIONAR O GENERO", "MASCULINO", "FEMENINO" }));
        cbgenero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbgeneroKeyPressed(evt);
            }
        });

        txtbi.setPlaceholder("Nº DO BI");
        txtbi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbiKeyPressed(evt);
            }
        });

        txttelefone.setPlaceholder("TELEFONE");
        txttelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelefoneActionPerformed(evt);
            }
        });
        txttelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttelefoneKeyPressed(evt);
            }
        });

        txtmorada.setPlaceholder("MORADA");
        txtmorada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmoradaActionPerformed(evt);
            }
        });
        txtmorada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtmoradaKeyPressed(evt);
            }
        });

        btnactualizar.setBackground(new java.awt.Color(255, 102, 0));
        btnactualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/salvar.png"))); // NOI18N
        btnactualizar.setText("ACTUALIZAR");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtmorada, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addComponent(btnactualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtnome, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addComponent(cbgenero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtbi, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addComponent(btnsalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txttelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbgenero, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(txtbi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(txtmorada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(txttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(btnactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(52, 58, 115));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/left.png"))); // NOI18N
        jLabel3.setText("VOLTAR");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtpesquisar.setPlaceholder("Pesquisar");
        txtpesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpesquisarKeyReleased(evt);
            }
        });

        tbcadastro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "null", "null", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbcadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbcadastroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbcadastro);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("REGISTO DE DIVIDAS");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DIVIDAS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        tbdivida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "  ", "  ", "  ", "  ", "  "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbdivida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbdividaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbdivida);

        txtdivida.setPlaceholder("DIGITE O VALOR DA DIVIDA");
        txtdivida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdividaActionPerformed(evt);
            }
        });
        txtdivida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdividaKeyPressed(evt);
            }
        });

        txtfatura.setPlaceholder("DGITE O Nº DA FACTURA");
        txtfatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfaturaActionPerformed(evt);
            }
        });
        txtfatura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfaturaKeyPressed(evt);
            }
        });

        try {
            txtdatadivi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtdatadivi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtdatadivi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtdatadivi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtdatadiviMouseClicked(evt);
            }
        });
        txtdatadivi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdatadiviActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("DATA");

        btndivida.setBackground(new java.awt.Color(255, 102, 0));
        btndivida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/salvar.png"))); // NOI18N
        btndivida.setText("ADICIONAR");
        btndivida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndividaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtdatadivi, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtdivida, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtfatura, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndivida, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdivida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtdatadivi, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndivida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PAGAMENTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        txtpagamento.setPlaceholder("VALOR A PAGAR");
        txtpagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpagamentoActionPerformed(evt);
            }
        });
        txtpagamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpagamentoKeyPressed(evt);
            }
        });

        try {
            txtdatapagamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtdatapagamento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtdatapagamento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtdatapagamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtdatapagamentoMouseClicked(evt);
            }
        });
        txtdatapagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdatapagamentoActionPerformed(evt);
            }
        });

        btnpagamento.setBackground(new java.awt.Color(255, 102, 0));
        btnpagamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/salvar.png"))); // NOI18N
        btnpagamento.setText("PAGAMENTO");
        btnpagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpagamentoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DATA");

        tbpagamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "null", "null", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbpagamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbpagamentoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbpagamento);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtpagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtdatapagamento)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(btnpagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdatapagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnpagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1029, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(txtpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txttelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefoneActionPerformed

    private void tbcadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbcadastroMouseClicked

        //codigo para o duplo clique
        if (evt.getClickCount() == 2) {
            //codigo do Joptiona 
            //declaramos uma vetor objecto que vai armazenar os itens selecionado
            Object[] recebe = {"EDITAR", "ELIMINAR", "DIVIDA", "CANCELAR"};
            int valor = (int) JOptionPane.showOptionDialog(this, "O QUE DESEJA?", "AVISO",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, recebe, recebe[3]);
            if (valor == 0) {
                codigo = (int) tbcadastro.getValueAt(tbcadastro.getSelectedRow(), 0);
                txtnome.setText((String) tbcadastro.getValueAt(tbcadastro.getSelectedRow(), 1));
                cbgenero.setSelectedItem((String) tbcadastro.getValueAt(tbcadastro.getSelectedRow(), 2));
                txtbi.setText((String) tbcadastro.getValueAt(tbcadastro.getSelectedRow(), 3));
                txtmorada.setText((String) tbcadastro.getValueAt(tbcadastro.getSelectedRow(), 4));
                txttelefone.setText((String) "" + tbcadastro.getValueAt(tbcadastro.getSelectedRow(), 5));
                btnactualizar.setText("ACTUALIZAR");
                btnsalvar.setVisible(false);
                txtdatadivi.setEnabled(!false);
                txtdivida.setEnabled(!false);
                txtfatura.setEnabled(!false);
                id++;
                v = 0;
            } else {
                if (valor == 1) {
                    apagar();
                    pesquisar("");
                } else {
                    codigo = (int) tbcadastro.getValueAt(tbcadastro.getSelectedRow(), 0);
                    txtdivida.requestFocus();
                    v = 3;
                }
            }

        }

    }//GEN-LAST:event_tbcadastroMouseClicked

    private void txtpesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesquisarKeyReleased
        // TODO add your handling code here:
        pesquisar(txtpesquisar.getText());
    }//GEN-LAST:event_txtpesquisarKeyReleased

    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
        // TODO add your handling code here:
        salvar();
        pesquisar("");
    }//GEN-LAST:event_btnsalvarActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        new Principal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void txtnomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            cbgenero.requestFocus();
        }
    }//GEN-LAST:event_txtnomeKeyPressed

    private void cbgeneroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbgeneroKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            txtbi.requestFocus();
        }
    }//GEN-LAST:event_cbgeneroKeyPressed

    private void txtbiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbiKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            txtmorada.requestFocus();
        }
    }//GEN-LAST:event_txtbiKeyPressed

    private void txttelefoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefoneKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefoneKeyPressed

    private void txtmoradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmoradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmoradaActionPerformed

    private void txtmoradaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmoradaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            txttelefone.requestFocus();
        }
    }//GEN-LAST:event_txtmoradaKeyPressed

    private void txtdividaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdividaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdividaActionPerformed

    private void txtdividaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdividaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdividaKeyPressed

    private void txtpagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpagamentoActionPerformed

    private void txtpagamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpagamentoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpagamentoKeyPressed

    private void txtdatapagamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdatapagamentoMouseClicked
    }//GEN-LAST:event_txtdatapagamentoMouseClicked

    private void txtdatapagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdatapagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdatapagamentoActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        // TODO add your handling code here:
        if (id == 0) {
            atualizar();
        } else {
            atualizar();
            v = 1;
        }
    }//GEN-LAST:event_btnactualizarActionPerformed
    private void tbdividaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbdividaMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            pag = (int) tbdivida.getValueAt(tbdivida.getSelectedRow(), 0);
            txtpagamento.setEnabled(!false);
            txtdatapagamento.setEnabled(!false);
            btnpagamento.setEnabled(!false);
            txtpagamento.requestFocus();

        }
    }//GEN-LAST:event_tbdividaMouseClicked
    private void btnpagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpagamentoActionPerformed
        // TODO add your handling code here:
        codidivida = (int) tbdivida.getValueAt(tbdivida.getSelectedRow(), 0);
        pagamento();
        list_pag();
    }//GEN-LAST:event_btnpagamentoActionPerformed

    private void txtfaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfaturaActionPerformed

    private void txtfaturaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfaturaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfaturaKeyPressed

    private void tbpagamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbpagamentoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbpagamentoMouseClicked

    private void txtdatadiviMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdatadiviMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdatadiviMouseClicked

    private void txtdatadiviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdatadiviActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdatadiviActionPerformed

    private void btndividaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndividaActionPerformed
        // TODO add your handling code here:
        dividas();
        listardivi();

    }//GEN-LAST:event_btndividaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DIVIDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DIVIDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DIVIDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DIVIDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DIVIDA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButton btnactualizar;
    private rojeru_san.RSButton btndivida;
    private rojeru_san.RSButton btnpagamento;
    private rojeru_san.RSButton btnsalvar;
    private javax.swing.JComboBox cbgenero;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbcadastro;
    private javax.swing.JTable tbdivida;
    private javax.swing.JTable tbpagamento;
    private rojeru_san.RSMTextFull txtbi;
    private javax.swing.JFormattedTextField txtdatadivi;
    private javax.swing.JFormattedTextField txtdatapagamento;
    private rojeru_san.RSMTextFull txtdivida;
    private rojeru_san.RSMTextFull txtfatura;
    private rojeru_san.RSMTextFull txtmorada;
    private rojeru_san.RSMTextFull txtnome;
    private rojeru_san.RSMTextFull txtpagamento;
    private rojeru_san.RSMTextFull txtpesquisar;
    private rojeru_san.RSMTextFull txttelefone;
    // End of variables declaration//GEN-END:variables

    private void salvar() {
        Mdevedor f = new Mdevedor();
        Cdevedor c = new Cdevedor();
        String nome = txtnome.getText();
        String genero = (String) cbgenero.getSelectedItem();
        String bi = txtbi.getText();
        int telefone = Integer.valueOf(txttelefone.getText());
        String morada = txtmorada.getText();

        if (!nome.isEmpty() && !bi.isEmpty() && !genero.isEmpty()) {
            f.setBi(bi);
            f.setGenero(genero);
            f.setNome(nome);
            f.setMorada(morada);
            f.setTelefone(telefone);
            f.setFuncionario(Integer.valueOf(idf));
            c.salvar(f);
        } else {
            f.mensagem("PRENCHA OS ESPAÇOS VAZIOS");
        }

        LIMPAR();
        txtpagamento.setEnabled(false);
        txtdatapagamento.setEnabled(false);
        btnpagamento.setEnabled(false);
        pesquisar("");

    }

    private void atualizar() {
        Mdevedor f = new Mdevedor();
        Cdevedor c = new Cdevedor();
        String nome = txtnome.getText();
        String genero = (String) cbgenero.getSelectedItem();
        String bi = txtbi.getText();
        String morada = txtmorada.getText();
        int telefone = Integer.valueOf(txttelefone.getText());
        if (txtbi.getText().equals("") || txtnome.getText().equals("") || txttelefone.getText().equals("")
                || cbgenero.getSelectedIndex() == 0 || txtmorada.getText().equals("")) {
            f.mensagem("PRENCHA OS ESPAÇOS VAZIOS");
        } else {
            f.setBi(bi);
            f.setGenero(genero);
            f.setNome(nome);
            f.setTelefone(telefone);
            f.setMorada(morada);
            f.setFuncionario(Integer.valueOf(idf));
            c.actualizar(f);
        }

        pesquisar("");
        LIMPAR();

    }

    public int pesquisar(String pesquisar) {
        int qtd = 0;
        Cdevedor f = new Cdevedor();
        DefaultTableModel dt = (DefaultTableModel) tbcadastro.getModel();
        Object[] recebe = {"CODIGO", "NOME", "GENERO", "BI", "MORADA", "TELEFONE"};
        dt.setColumnIdentifiers(recebe);
        dt.setNumRows(0);
        for (Mdevedor m : f.pesquisar(pesquisar)) {
            Object[] dado = {m.getIdt(), m.getNome(), m.getGenero(), m.getBi(), m.getMorada(), m.getTelefone()};
            dt.addRow(dado);
            if (m.getIdt() > 0) {
                qtd++;
            }
        }
        return qtd;
    }

    private void LIMPAR() {
        txtbi.setText("");
        txtnome.requestFocus();
        txtnome.setText("");
        txttelefone.setText("");
        cbgenero.setSelectedIndex(0);
        txtmorada.setText("");
        txtdatapagamento.setText("");
        txtdivida.setText("");
        txtpagamento.setText("");
        txtbi.setEnabled(!false);
        txtmorada.setEnabled(!false);
        txtnome.setEnabled(!false);
        cbgenero.setEnabled(!false);
        txttelefone.setEnabled(!false);
        txtdatapagamento.setEnabled(!false);
        txtdivida.setEnabled(!false);
        txtpagamento.setEnabled(!false);
    }

    private void apagar() {
        Mdevedor md = new Mdevedor();//instanciamos a modal
        int valor = (int) tbcadastro.getValueAt(tbcadastro.getSelectedRow(), 0);//declaramos uma variavel que recebe a um valor da tabela caso seja seleciona e é convertido
        md.setIdt(valor);
        Cdevedor cd = new Cdevedor();//instanciamos a control
        cd.apagar(md);
        listardivi();
    }

    private void dividas() {
        codigo = (int) tbcadastro.getValueAt(tbcadastro.getSelectedRow(), 0);
        divida = Double.valueOf(txtdivida.getText());
        fatura = Integer.valueOf(txtfatura.getText());
        String dat = txtdatadivi.getText();
        Mdivida m = new Mdivida();
        Cdividas d = new Cdividas();
        if (txtdatadivi.getText().equals("    /  /  ") || txtdivida.getText().equals("") || txtfatura.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "PRENCHA OS CAMPOS VAZIOS");
        } else {
            m.setData(dat);
            m.setIddevedor(codigo);
            m.setN_factura(fatura);
            m.setTotal(divida);
            d.salvar(m);
        }
        txtpagamento.setEnabled(false);
        txtdatapagamento.setEnabled(false);
        btnpagamento.setEnabled(false);
        txtdivida.setText("");
        txtfatura.setText("");
        txtdatapagamento.setText("");
    }

    private void atualizardivida() {
        codigodiv = (int) tbdivida.getValueAt(tbdivida.getSelectedRow(), 0);
        String divi = txtdivida.getText();
        String fatur = txtfatura.getText();
        String dat = txtdatadivi.getText();
        valor_pago = Double.valueOf(txtpagamento.getText());
        Mdivida m = new Mdivida();
        Cdividas d = new Cdividas();
        if (txtdatadivi.getText().equals("    /  /  ") || txtdivida.getText().equals("") || txtfatura.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "PRENCHA OS CAMPOS VAZIOS");
        } else {
            divi += divi;
            m.setData("" + dat);
            m.setIddevedor(codigodiv);
            m.setN_factura(Integer.valueOf(fatur));
            m.setTotal(Integer.valueOf(divi));
            d.salvar(m);
            if (v == 1) {
                total = Integer.valueOf(divi) - valor_pago;
                m.setData("" + dat);
                m.setIddevedor(codigodiv);
                m.setN_factura(Integer.valueOf(fatur));
                m.setTotal(total);
                d.actualizar(m);
            }
        }
        txtdivida.setText("");
        txtfatura.setText("");
        txtdatapagamento.setText("");
        list_pag();
        listardivi();
    }

    private void listardivi() {
        Cdividas d = new Cdividas();
        DefaultTableModel dt = (DefaultTableModel) tbdivida.getModel();
        Object[] recebe = {"CODIGO", "NOME", "TELEFONE", "ENDEREÇO", "DIVIDA", "DATA DA DIVIDA", "Nº DA FACTURA"};
        dt.setColumnIdentifiers(recebe);
        dt.setNumRows(0);
        for (Vdivida m : d.pesquisar()) {
            Object[] dado = {m.getCodigo(), m.getNome(), m.getTelefone(), m.getMorada(), m.getDivida(), m.getData(), m.getN_factura()};
            dt.addRow(dado);
        }
    }

    private void pagamento() {
        Cpagamento c = new Cpagamento();
        Mpagamento p = new Mpagamento();
        valor_pago = Double.valueOf(txtpagamento.getText());
        String datapagamento = txtdatapagamento.getText();
        if (txtpagamento.getText().equals("") || txtdatapagamento.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "POR FAVOR PRENCHA OS VALOR");
        } else {
            p.setIddivida(pag);
            p.setValor_pago(valor_pago);
            p.setDatapagamento(datapagamento);
            c.salvar(p);
            atualizardivida();
            v = 1;
        }
        list_pag();
        txtdatapagamento.setText("");
        txtpagamento.setText("");
    }

    private void list_pag() {
        Cpagamento d = new Cpagamento();
        DefaultTableModel dt = (DefaultTableModel) tbpagamento.getModel();
        Object[] recebe = {"CODIGO", "NOME", "VALOR PAGO", "DATA DO PAGAMENTO"};
        dt.setColumnIdentifiers(recebe);
        dt.setNumRows(0);
        for (vpagamento m : d.pesquisar()) {
            Object[] dado = {m.getCodigo(), m.getNome(), m.getValor(), m.getData()};
            dt.addRow(dado);
        }
    }
}
