/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import Control.Clogin;
import Control.Cvenda;
import Modal.Mvenda;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TEODORO
 */
public class Venda extends javax.swing.JFrame {

    /**
     * Creates new form Venda
     */
    double total = 0;
    String idf, cargo;

    public Venda() {
        initComponents();
        pesquisar("");
        txtdatavenda.setText(data());
        Clogin l = new Clogin();//INSTANCIAMOS A CLASSE CONTROL DA LOGIN NO CONSTRUTOR
        lbnome.setText(l.recuprarValor(1));//RECUPERAMOS O VALOR DA LOGIN FUNCIONARIO
        idf = l.recuprarValor(0);
        cargo = l.recuprarValor(2);
        lbempresa.setText(new Principal().empresa());
        lbtrocodeixado.setText(new Principal().LISTAtroco());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbnome = new javax.swing.JLabel();
        lbempresa = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtdatavenda = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbfaturados = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbpesquisar = new javax.swing.JTable();
        txtpesquisar = new rojeru_san.RSMTextFull();
        jPanel7 = new javax.swing.JPanel();
        txtcliente = new rojeru_san.RSMTextFull();
        txttotalcompra = new rojeru_san.RSMTextFull();
        txtvalorpago = new rojeru_san.RSMTextFull();
        txttroco = new rojeru_san.RSMTextFull();
        btnsalvar = new rojeru_san.RSButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnadministrador = new rojeru_san.RSButton();
        lbtrocodeixado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(52, 58, 115));

        lbnome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbnome.setForeground(new java.awt.Color(255, 255, 255));
        lbnome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbnome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pichon/icons8_administrator_male_40px.png"))); // NOI18N

        lbempresa.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbempresa.setForeground(new java.awt.Color(255, 255, 255));
        lbempresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbempresa.setText("SOFTWARE");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DATA DA VENDA");

        try {
            txtdatavenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtdatavenda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtdatavenda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lbnome, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtdatavenda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbempresa, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbempresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdatavenda, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbnome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(52, 58, 115));
        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        tbfaturados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "  ", "  ", " ", " "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbfaturados);

        jLabel3.setFont(new java.awt.Font("Ink Free", 1, 12)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Close_20px_2.png"))); // NOI18N
        jLabel3.setText("APAGAR");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Ink Free", 1, 12)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icons8_unavailable_20px_1.png"))); // NOI18N
        jLabel4.setText("CANCELAR");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        tbpesquisar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbpesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbpesquisarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbpesquisar);

        txtpesquisar.setPlaceholder("PESQUISAR");
        txtpesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtpesquisarMouseReleased(evt);
            }
        });
        txtpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpesquisarActionPerformed(evt);
            }
        });
        txtpesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpesquisarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(txtpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(52, 58, 115));

        txtcliente.setPlaceholder("NOME DO CLIENTE");
        txtcliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtclienteKeyPressed(evt);
            }
        });

        txttotalcompra.setText("TOTAL DA COMPRA");
        txttotalcompra.setEnabled(false);
        txttotalcompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalcompraActionPerformed(evt);
            }
        });

        txtvalorpago.setPlaceholder("DIGITE O VALOR PAGO");
        txtvalorpago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtvalorpagoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtvalorpagoKeyReleased(evt);
            }
        });

        txttroco.setText("TROCO");
        txttroco.setEnabled(false);

        btnsalvar.setBackground(new java.awt.Color(255, 102, 0));
        btnsalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/salvar.png"))); // NOI18N
        btnsalvar.setText("FINALIZAR");
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Bauhaus 93", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("FINALIZAR VENDA");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/FECHAR.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        btnadministrador.setBackground(new java.awt.Color(255, 102, 0));
        btnadministrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icons8_money_bag_38px.png"))); // NOI18N
        btnadministrador.setText("FECHO DIÁRIO");
        btnadministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadministradorActionPerformed(evt);
            }
        });

        lbtrocodeixado.setText("DEIXADO PELO GESTOR");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txttotalcompra, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtcliente, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                .addComponent(txtvalorpago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txttroco, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnadministrador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbtrocodeixado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(txtcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txttotalcompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txttroco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtvalorpago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnadministrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbtrocodeixado)
                .addGap(108, 108, 108)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(459, 459, 459))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(588, 588, 588)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
        // TODO add your handling code here:
        finalizar();
        pesquisar("");
    }//GEN-LAST:event_btnsalvarActionPerformed
    String id;
    int quantida = 0;

    private void tbpesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbpesquisarMouseClicked
        // TODO add your handling code here:
        id = (String) tbpesquisar.getValueAt(tbpesquisar.getSelectedRow(), 0);
        double preco = Double.valueOf((String) tbpesquisar.getValueAt(tbpesquisar.getSelectedRow(), 2));
        int qtdExistente = Integer.valueOf((String) tbpesquisar.getValueAt(tbpesquisar.getSelectedRow(), 3));
        String nome = (String) tbpesquisar.getValueAt(tbpesquisar.getSelectedRow(), 1);
        if (evt.getClickCount() == 2) {
            quantida = Integer.valueOf(JOptionPane.showInputDialog("DIGITE A QUANTIDADE PRETENDIDA"));
            if (quantida > 0 & quantida <= qtdExistente) {
                double valor = quantida * preco;
                total += valor;
                DefaultTableModel dt = (DefaultTableModel) tbfaturados.getModel();
                Object[] titulo = {"CODIGO", "NOME / DESCRIÇÃO /CATEGORIA", "QUANTIDADE", "SUBTOTAL"};
                dt.setColumnIdentifiers(titulo);
                Object[] recebe = {id, nome, quantida, valor};
                dt.addRow(recebe);
            } else {
                JOptionPane.showMessageDialog(this, "A QUANTIDADE PRETENDIDA NÃO PODE SER MENOR QUE ZERO"
                        + " E NEM MAIOR QUE A QUANTIDADE EXISTENTE NO STOCK");
            }
        }
        txttotalcompra.setText("TOTAL DA COMPRA: " + total + " KZ");

    }//GEN-LAST:event_tbpesquisarMouseClicked

    private void txttotalcompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalcompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalcompraActionPerformed

    private void txtpesquisarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpesquisarMouseReleased
        // TODO add your handling code here:
        pesquisar(txtpesquisar.getText());

    }//GEN-LAST:event_txtpesquisarMouseReleased

    private void txtpesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesquisarKeyReleased
        // TODO add your handling code here:
    pesquisar(txtpesquisar.getText());
    }//GEN-LAST:event_txtpesquisarKeyReleased

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        txtpesquisar.setText("");
        txtpesquisar.requestFocus();
        if (tbfaturados.getSelectedRow() > -1) {
            DefaultTableModel dtm = (DefaultTableModel) tbfaturados.getModel();
            double valor = (double) tbfaturados.getValueAt(tbfaturados.getSelectedRow(), 3);
            total = total - valor;
            txttotalcompra.setText("TOTAL DA COMPRA: " + total + " KZ");
            dtm.removeRow(tbfaturados.getSelectedRow());
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void txtvalorpagoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvalorpagoKeyReleased
        // TODO add your handling code here:
        troco(Double.valueOf(txtvalorpago.getText()));
    }//GEN-LAST:event_txtvalorpagoKeyReleased

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        DefaultTableModel remover = (DefaultTableModel) tbfaturados.getModel();
        remover.setNumRows(0);
        total = 0;
        txttotalcompra.setText("TOTAL DA COMPRA");
        txtpesquisar.setText("");
        txtpesquisar.requestFocus();

    }//GEN-LAST:event_jLabel4MouseClicked

    private void txtclienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtclienteKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            txtvalorpago.requestFocus();
        }
    }//GEN-LAST:event_txtclienteKeyPressed

    private void txtvalorpagoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvalorpagoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            finalizar();
            pesquisar("");
        }
    }//GEN-LAST:event_txtvalorpagoKeyPressed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        if (cargo.equalsIgnoreCase("Gerente")) {
            new Principal().setVisible(true);
            this.dispose();
        } else {
            new Login().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void btnadministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadministradorActionPerformed
        new Cvenda().impressaoDiaria(idf, txtdatavenda.getText());

    }//GEN-LAST:event_btnadministradorActionPerformed

    private void txtpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpesquisarActionPerformed
        // TODO add your handling code here:
        pesquisarbarra(txtpesquisar.getText());
    }//GEN-LAST:event_txtpesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Venda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButton btnadministrador;
    private rojeru_san.RSButton btnsalvar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbempresa;
    private javax.swing.JLabel lbnome;
    private javax.swing.JLabel lbtrocodeixado;
    private javax.swing.JTable tbfaturados;
    private javax.swing.JTable tbpesquisar;
    private rojeru_san.RSMTextFull txtcliente;
    private javax.swing.JFormattedTextField txtdatavenda;
    private rojeru_san.RSMTextFull txtpesquisar;
    private rojeru_san.RSMTextFull txttotalcompra;
    private rojeru_san.RSMTextFull txttroco;
    private rojeru_san.RSMTextFull txtvalorpago;
    // End of variables declaration//GEN-END:variables

    private void pesquisar(String pesquisar) {
        Cvenda f = new Cvenda();
        DefaultTableModel dt = (DefaultTableModel) tbpesquisar.getModel();
        Object[] recebe = {"CODIGO", "NOME / DESCRIÇÃO /CATEGORIA", "PREÇO", "QUANTIDADE", "CATEGÓRIA"};
        dt.setColumnIdentifiers(recebe);
        dt.setNumRows(0);
        for (Modal.MviewEntrada m : f.pesquisar(pesquisar)) {
            Object[] dado = {m.getCodigo(), m.getNome() + " " + m.getDescricao(), m.getPreco(),
                m.getQuantidade(), m.getCategoria()};
            dt.addRow(dado);
        }
    }

    private void pesquisarbarra(String pesquisar) {
        Cvenda f = new Cvenda();
        DefaultTableModel dtm = (DefaultTableModel) tbpesquisar.getModel();
        Object[] recebe = {"CODIGO", "NOME / DESCRIÇÃO /CATEGORIA", "PREÇO", "QUANTIDADE", "CATEGÓRIA"};
        dtm.setColumnIdentifiers(recebe);
        dtm.setNumRows(0);
        int preco = 0;
        int c = 0;
        String nome = "";
        for (Modal.MviewEntrada m : f.pesquisar(pesquisar)) {
            Object[] dado = {m.getCodigo(), m.getNome() + " " + m.getDescricao(), m.getPreco(),
                m.getQuantidade(), m.getCategoria()};
            id = m.getCodigo();
            nome = m.getNome();
            preco = Integer.valueOf(m.getPreco());
            dtm.addRow(dado);
            c++;
        }
        if (c != 0 & c < 2) {
            quantida = Integer.valueOf(JOptionPane.showInputDialog("DIGITE A QUANTIDADE PRETENDIDA"));
            if (quantida > 0) {
                int valor = quantida * preco;
                total += valor;
                DefaultTableModel dt = (DefaultTableModel) tbfaturados.getModel();
                Object[] titulo1 = {"CODIGO","NOME / DESCRIÇÃO /CATEGORIA", "QUANTIDADE", "SUBTOTAL"};
                dt.setColumnIdentifiers(titulo1);
                Object[] recebe1 = {id, nome, quantida, valor};
                dt.addRow(recebe1);

            } else {
                JOptionPane.showMessageDialog(this, "A QUANTIDADE PRETENDIDA NÃO PODE SER MENOR QUE ZERO E NEM MAIOR QUE A QUANTIDADE"
                        + "EXISTENTE NO STOCK");
            }
            txtpesquisar.setText("");
            txtpesquisar.requestFocus();
            txttotalcompra.setText("TOTAL DA COMPRA: " + total + " KZ");
        }

    }

    private String data() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        return s.format(d);
    }

    private String dataf() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyyMMddHHmmss");
        return s.format(d);
    }
    double dinheiro = 0, v = 0;

    private void troco(double pago) {
        v = pago;
        dinheiro = v - total;
        txttroco.setText("TROCO: " + dinheiro + " KZ");
    }

    private void finalizar() {
        double valor = Double.valueOf(txtvalorpago.getText());
        if (valor < total) {
            JOptionPane.showMessageDialog(this, "VALOR INSUFICIENTE");
            txtvalorpago.requestFocus();
        } else {
            vender();
        }
    }

    private void vender() {

        DefaultTableModel dtm = (DefaultTableModel) tbfaturados.getModel();
        String datav = txtdatavenda.getText();
        String fatura = dataf();
        for (int i = 0; i < tbfaturados.getRowCount(); i++) {
            String idp = (String) tbfaturados.getValueAt(i, 0);
            int qtdrequerida = (int) tbfaturados.getValueAt(i, 2);
            double totalcompra = (double) tbfaturados.getValueAt(i, 3);
            Mvenda m = new Mvenda();
            m.setDatavenda(datav);
            m.setFatura(fatura);
            m.setIdproduto(idp);
            m.setQuantidaderequerida("" + qtdrequerida);
            m.setTotalcompra("" + totalcompra);
            m.setIdfuncionario(idf);
            new Cvenda().salvar(m);

        }
        //LIMPAR CAMPOS

        new Cvenda().impressao(dinheiro, v, fatura, txtcliente.getText());
        total = 0;
        txtvalorpago.setText("");
        txtcliente.setText("");
        //txtcliente.requestFocus();
        txttotalcompra.setText("TROTAL DA COMPRA : 0 KZ");
        txttroco.setText("TROCO:  00 KZ");
        dtm.setNumRows(0);
        dinheiro = v = 0;
    }

}
